import { defineConfig } from "eslint/config";
import globals from "globals";
import tseslint from "typescript-eslint";
import pluginN from "eslint-plugin-n";
import pluginImport from "eslint-plugin-import";
import pluginPromise from "eslint-plugin-promise";
import pluginSecurity from "eslint-plugin-security";
import pluginUnicorn from "eslint-plugin-unicorn";
import pluginSonar from "eslint-plugin-sonarjs";
import perfectionist from "eslint-plugin-perfectionist";
import * as regexpPlugin from "eslint-plugin-regexp";

export default defineConfig([
  tseslint.configs.recommended,
  tseslint.configs.recommendedTypeChecked,
  tseslint.configs.strict,
  pluginN.configs["flat/all"],
  pluginImport.flatConfigs.recommended,
  pluginImport.flatConfigs.errors,
  pluginImport.flatConfigs.warnings,
  pluginImport.flatConfigs.typescript,
  pluginPromise.configs["flat/recommended"],
  pluginSonar.configs.recommended,
  pluginSecurity.configs.recommended,
  pluginUnicorn.configs.recommended,
  perfectionist.configs["recommended-alphabetical"],
  regexpPlugin.configs["flat/recommended"],
  {
    files: ["**/*.{js,mjs,cjs,ts,mts,cts}"],
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: "module",
      globals: globals.node,
      parser: tseslint.parser,
      parserOptions: {
        project: "./tsconfig.json",
        tsconfigRootDir: process.cwd(),
      },
    },
    rules: {
      "n/no-missing-import": "off",
      "n/no-unsupported-features/es-syntax": "off",
      "import/order": [
        "error",
        {
          groups: [
            "builtin",
            "external",
            "internal",
            "parent",
            "sibling",
            "index",
          ],
          "newlines-between": "always",

          alphabetize: {
            order: "asc",
            caseInsensitive: true,
          },
        },
      ],
      "n/file-extension-in-import": "off",
      "perfectionist/sort-imports": 0,
      "promise/catch-or-return": "error",
      "promise/no-return-wrap": "error",
      "security/detect-object-injection": "off",
      "unicorn/better-regex": "error",
      "unicorn/filename-case": ["error", { case: "kebabCase" }],
      "unicorn/prefer-query-selector": "error",
      "unicorn/prefer-node-protocol": "error",
      "unicorn/throw-new-error": "error",
      "unicorn/no-array-for-each": "warn",
      "unicorn/no-null": "off",
      "unicorn/number-literal-case": "off",
      "unicorn/filename-case": "off",
      "sonarjs/cognitive-complexity": ["warn", 200],
      "sonarjs/no-identical-functions": "error",
      "sonarjs/no-nested-switch": "error",
      "sonarjs/no-small-switch": "error",
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/prefer-optional-chain": "error",
      "@typescript-eslint/unified-signatures": "off",
      "@typescript-eslint/no-misused-promises": "error",
      "@typescript-eslint/no-unnecessary-type-arguments": "error",
      "@typescript-eslint/dot-notation": "error",
      "@typescript-eslint/no-non-null-assertion": "off",
      "@typescript-eslint/ban-ts-comment": [
        "error",
        { "ts-ignore": "allow-with-description" },
      ],
      "no-unused-vars": ["error", { args: "none", ignoreRestSiblings: true }],
      "prefer-const": "error",
      "no-console": ["warn", { allow: ["warn", "error", "info"] }],
      "no-use-before-define": ["error", { functions: false, classes: true }],
      curly: ["error", "all"],
      "no-var": "error",
      "prefer-arrow-callback": "warn",
      "no-duplicate-imports": "error",
      "no-empty": "warn",
      "no-extra-semi": "error",
      "no-extra-boolean-cast": "warn",
      "no-dupe-keys": "error",
      "no-implied-eval": "error",
      "no-new-wrappers": "error",
      "array-callback-return": "error",
      "for-direction": "error",
      "no-compare-neg-zero": "error",
      "no-cond-assign": ["error", "always"],
      "no-debugger": "error",
      "no-dupe-else-if": "error",
      "no-duplicate-case": "error",
      "no-irregular-whitespace": "error",
      "no-self-compare": "error",
      "no-sparse-arrays": "error",
      "no-template-curly-in-string": "error",
      "no-unexpected-multiline": "error",
      "no-unmodified-loop-condition": "error",
      complexity: ["warn", 64],
      "max-nested-callbacks": ["warn", 10],
      "no-lonely-if": "warn",
      "no-negated-condition": "warn",
      yoda: ["error", "never"],
      quotes: ["error", "double"],
      semi: ["error", "always"],
      "linebreak-style": ["error", "unix"],
      "no-trailing-spaces": "error",
      "eol-last": ["error", "always"],
    },
  },
]);
